# project-repo/.github/workflows/main.yml

name: Main Workflows

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: sreekanth014/2407reusable/.github/workflows/build-test.yml@master
    with:
      project-dir: .
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
